### ISSUE TITLE
LocaleSetting can't overwrite the browser locale setting

### ISSUE THREAD

**Issue by zhll2046** [Microsoft/PowerBI-JavaScript#269]
LocaleSettings is applied in my Javascript in the way in [this thread](https://community.powerbi.com/t5/Issues/Power-BI-Embedded-localeSetting-is-not-applying-the-setting/idi-p/276077), however it won't overwrite the browser locale setting. Say, if my browser language is in Chinese, the date, currency format shows in Chinese, ignoring the fr/en LocaleSetting in JS.

Is this a bug or do you have any further guidance on how to apply the localeSetting correctly? Any demo sample is appreciated.

**Comment by zhll2046** [comment]
@craigb @sirui-sun

**Comment by iwollmann** [comment]
I have the same issue here.

**Comment by ali-hamud** [comment]
Hi,
we will try to get a repro and update after that.

**Comment by ArinaHantsis** [comment]
Hey @zhll2046,
I've just tested it and Locale Settings applied from JavaScript were applied and reflected for my data independent of the browser or OS settings.
I think there was an issue with it not only for Embedded but for PowerBI.com in general and it should get resolved by Nov 8th in all production clusters.

**Comment by mortenf** [comment]
This is still an issue, please fix.

**Comment by ali-hamud** [comment]
Documentation fixed. thanks.
Do you still have a problem?

**Comment by mortenf** [comment]
Yes, there is still a problem: The settings are not respected, the browser's settings override.

Even though I have the following in my page, I am able to switch browser language preferences (order) and have the resulting Power BI report reflect that, after a reload:

```
var report = powerbi.embed($('#reportContainer')[0],
            {
                type: 'report',
                tokenType: models.TokenType.Embed,
                accessToken: "...",
                embedUrl: "...",
                id: "...",
                permissions: models.Permissions.All,
                filters: [ ... ],
                settings: {
                    filterPaneEnabled: false,
                    navContentPaneEnabled: false,
                    localeSettings: { language: "en", formatLocale: "en-US" }
                }
            });
```

Verified today in IE11, Chrome and Firefox.

**Comment by mortenf** [comment]
This seems to be working now.

**Comment by ali-hamud** [comment]
Glad it works for you. I tried it as well and it works. closing the issue.
